version: '3.1'
services:
  app:
      container_name: app-springboot-postgresql
      image: lev.jar
      build: ./
      ports:
        - "8080:8080"
      depends_on:
        - dbpostgresql
        - adminer
  dbpostgresql:
      image: postgres
      ports:
        - "5432:5432"
      volumes:
        # Persist the data between container invocations
        #- ./my-postgres.conf:/etc/postgresql.conf
        - ./dataRami.sql:/var/lib/postgresql/data
      #- ./data.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
        - PGDATA=/var/lib/postgresql/data


  adminer:
      image: adminer
      restart: always
      ports:
        - 8000:8000

