version: '3.1'
services:
  app:
      container_name: app-springboot-postgresql
      image: lev.jar
      build: ./
      ports:
        - "8080:8080"
      depends_on:
        - dbpostgresql

  dbpostgresql:
      image: library
      ports:
        - "5434:5432"
      volumes:
        # Persist the data between container invocations
        #- ./my-postgres.conf:/etc/postgresql.conf
        - ./datapostgres.sql:/var/lib/postgresql/data
      #- ./data.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        - POSTGRES_PASSWORD=undergroundpscrew32
        - POSTGRES_USER=leva5363
        - POSTGRES_DB=Library
        - PGDATA=/var/lib/postgresql/data

